name: Publish the testing repository
on:
    push:
        branches:
            - testing
jobs:
    images:
        name: Publish images
        runs-on: ubuntu-latest
        strategy:
            matrix:
                image: [
                    base,
                    qt,
                    rust
                ]
        steps:
            - name: Checkout the Git repository
              uses: actions/checkout@v2
            - name: Publish images
              uses: docker/build-push-action@v1
              with:
                  tags: ${{ github.ref }}
                  build_args: BRANCH=${{ github.ref }}
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}
                  registry: docker.pkg.github.com
                  repository: ${{ github.repository }}/${{ matrix.image }}
                  path: image/${{ matrix.image }}
    packages:
        needs: images
        name: Publish packages
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the Git repository
              uses: actions/checkout@v2
            - name: Publish packages
              uses: ./.github/actions/publish-packages
              env:
                  REMOTE_PATH: /srv/toltec/${{ github.ref }}
                  REMOTE: ${{ secrets.REMOTE }}
                  SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
                  SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
