name: Publish the testing repository
on:
    push:
        branches:
            - testing
jobs:
    images:
        name: Build and publish images
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the Git repository
              uses: actions/checkout@v2
            - name: Build and publish images
              run: |
                  echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
                  ./scripts/build-images -p image
    packages:
        needs: images
        name: Build and publish packages
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the Git repository
              uses: actions/checkout@v2
            - name: Build packages
              run: ./scripts/build-repo package build
            - uses: actions/upload-artifact@v2
              with:
                name: repo
                path: build/repo
