name: stable
on:
    push:
        branches:
            - stable
jobs:
    images:
        name: Build and publish images
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the Git repository
              uses: actions/checkout@v2
            - name: Build and publish images
              run: |
                echo "${{ secrets.CR_PAT }}" | docker login ghcr.io -u "$GITHUB_ACTOR" --password-stdin
                ./scripts/build-images -p image
    packages:
        needs: images
        name: Build and publish packages
        runs-on: ubuntu-latest
        steps:
            - name: Checkout the Git repository
              uses: actions/checkout@v2
            - name: Build packages
              run: ./scripts/build-repo package build
            - name: Define current channel
              run: |
                echo "::set-env name=CHANNEL::stable"
            - name: Transfer packages and index
              run: |
                mkdir -p private
                chmod 700 private
                echo "${{ secrets.SSH_PRIVATE_KEY }}" > private/id_rsa
                echo "${{ secrets.SSH_KNOWN_HOSTS }}" > private/known_hosts
                chmod 600 private/*
                rsync -avz \
                    -e "ssh -i private/id_rsa -o UserKnownHostsFile=private/known_hosts" \
                    build/repo/ "${{ secrets.REMOTE }}":/srv/toltec/"$CHANNEL"
